74 create component for chore frequency
Razew/suvnet23-household-backsidegang pull request #103
Opened 2024-10-23 17:38 UTC by robinLundahl

2024-10-23 21:48 UTC, Razew requested changes
Looks good for the most part, just take a look at these things and we should be all good!

2024-10-23 21:48 UTC, Razew commented on components/ChoreFrequency.tsx
> +import * as React from 'react';
Remove this as it isn't needed
```suggestion

```

2024-10-23 21:48 UTC, Razew commented on components/ChoreFrequency.tsx
> +  const [isPressed, setIsPressed] = React.useState(false);
Same as above, .React isn't necessary
```suggestion
  const [value, setValue] = useState(7);
  const [isPressed, setIsPressed] = useState(false);
```

2024-10-23 21:48 UTC, Razew commented on components/ChoreFrequency.tsx
> +const ChoreFrequency = () => {
For consistency write component as a function
```suggestion
export default function ChoreFrequency() {
```

2024-10-23 21:48 UTC, Razew commented on components/ChoreFrequency.tsx
> +    alignItems: 'center',
I'm not sure if this is required, seeing as it's a child of the <View> that already has alignItems: 'center' on it. I could be mistaken though, so please try it out to be on the safe side!
```suggestion

```

2024-10-23 21:48 UTC, Razew commented on components/ChoreFrequency.tsx
> +export default ChoreFrequency;
Remove this after changing ChoreFrequency to export default function
```suggestion

```

2024-10-23 22:36 UTC, Razew commented
Just as a heads up for future us: the various hardcoded style colors will override the theme

2024-10-24 02:22 UTC, robinLundahl commented on components/ChoreFrequency.tsx
> +import * as React from 'react';
fixed

2024-10-24 02:23 UTC, robinLundahl commented on components/ChoreFrequency.tsx
> +const ChoreFrequency = () => {
fixed

2024-10-24 02:23 UTC, robinLundahl commented on components/ChoreFrequency.tsx
> +  const [isPressed, setIsPressed] = React.useState(false);
fixed

2024-10-24 02:23 UTC, robinLundahl commented on components/ChoreFrequency.tsx
> +    alignItems: 'center',
fixed

2024-10-24 02:23 UTC, robinLundahl commented on components/ChoreFrequency.tsx
> +export default ChoreFrequency;
fixed

2024-10-24 02:24 UTC, robinLundahl commented
Awesome feedback! This is a great way of learning and get reminded of "slarvfel"!

2024-10-24 08:53 UTC, Razew approved these changes
Sweet, good job!

2024-10-24 08:53 UTC, merged