19 register screen
Razew/suvnet23-household-backsidegang pull request #62
Opened 2024-10-19 10:25 UTC by ghostworker94

2024-10-19 13:13 UTC, Razew requested changes

2024-10-19 13:13 UTC, Razew commented on screens/LoginScreen.tsx
> +      Alert.alert('Error', 'Invalid username or password');
I would suggest using Paper's equivalent of RN's Alert instead. It's called Dialog:
https://callstack.github.io/react-native-paper/docs/components/Dialog/

That way things will look more uniform and it will get theme applied to it and so on!

2024-10-19 13:13 UTC, Razew commented on screens/LoginScreen.tsx
> +export type Props = NativeStackScreenProps<RootStackParamList, 'Login'>;
Does this need to be exported?

2024-10-19 13:13 UTC, Razew commented on screens/LoginScreen.tsx
> +export const LoginScreen = ({ navigation }: Props) => {
I would suggest making this change, it aligns more with best practices (I believe). Or if you want you can still have it this way, but make it the default export at least!
```suggestion
export default function LoginScreen({ navigation }: Props) {
```
Please note that you will have to update the import in RootStackNavigator back to (if you make it the default export
): `import LoginScreen from '../screens/LoginScreen';`

2024-10-19 13:13 UTC, Razew commented on navigators/RootStackNavigator.tsx
> +import { LoginScreen } from '../screens/LoginScreen';
```suggestion
import LoginScreen from '../screens/LoginScreen';
```
_(Check suggestion in LoginScreen.tsx first)_

2024-10-19 13:13 UTC, Razew commented on types/types.ts
> +  loggedIn: boolean;
Does adding this to the type solve persistent login between sessions?
If not, is it needed? Because if you successfully log in, the global state "should/could" store the current user.

Something like this (not added to this file ofc):
`type UserState = {
  current?: User; // Logged in user`

and something like:
`const initialState: UserState = {
  current: undefined, // Logged in user
`

2024-10-19 13:13 UTC, Razew commented on screens/LoginScreen.tsx
> +      if (loginUser.fulfilled.match(resultAction)) {
Most of this stuff is handled in the thunk reducer already, right? I'm sure this works, but I think the idea is to instead read from the AuthState (with useAppSelector) to see if it was a success or not (like reading if error is something or null). 

And I know, it feels weird to do it that way in a sense, coming from C#

2024-10-19 13:13 UTC, Razew commented on screens/RegisterScreen.tsx
> +      if (createUser.fulfilled.match(resultAction)) {
See comment on handleLogin in LoginScreen (same comment here basically)

2024-10-19 14:08 UTC, ghostworker94 commented on screens/LoginScreen.tsx
> +      if (loginUser.fulfilled.match(resultAction)) {
i dont know any other way of doing it

2024-10-19 14:09 UTC, ghostworker94 commented on navigators/RootStackNavigator.tsx
> +import { LoginScreen } from '../screens/LoginScreen';
didnt work that way

2024-10-19 14:15 UTC, ghostworker94 commented on screens/LoginScreen.tsx
> +      Alert.alert('Error', 'Invalid username or password');
can use dialog, Argument of type 'string' is not assignable to parameter of type 'Props'.ts(2345)

2024-10-19 15:23 UTC, Razew commented on screens/LoginScreen.tsx
> +      Alert.alert('Error', 'Invalid username or password');
Yeah you gotta set title and/or the text body with <Dialog.Title>Title here</Dialog.Title>
And the rest is in the "Usage" example on the page I sent.

Come to think of it, you probably wouldn't want a pop-up each time you fail a login though (would normally be some red text by input field or something I guess?). Oh well, might look fancy at least!

Ofc we can also just create an issue for the visual aspects to do at a later date

2024-10-19 15:24 UTC, Razew commented on navigators/RootStackNavigator.tsx
> +import { LoginScreen } from '../screens/LoginScreen';
It should work if the LoginScreen function is the default export, otherwise it won't ^^

2024-10-19 15:31 UTC, Razew commented on screens/LoginScreen.tsx
> +      if (loginUser.fulfilled.match(resultAction)) {
In the bankvalvet code you can see another way of doing it, but assuming this works, we can just roll with it ^^

2024-10-21 16:21 UTC, Razew requested changes

2024-10-21 16:21 UTC, Razew commented on screens/RegisterScreen.tsx
> +      navigation.navigate('HomeNavigator');
Replace so that successful sign up means you get redirected to HomeNavigator without the ability to go back to this screen when logged in
```suggestion
      navigation.replace('HomeNavigator');
```

2024-10-21 16:21 UTC, Razew commented on screens/RegisterScreen.tsx
> +              onPress={() => handleRegister()}
No need to create a "new" function since it doesn't take any parameters
```suggestion
              onPress={handleRegister}
```

2024-10-21 16:21 UTC, Razew commented on screens/RegisterScreen.tsx
> +              {loading ? 'Loggin in' : 'Register'}
To reflect the correct action/page
```suggestion
              {loading ? 'Registering...' : 'Register'}
```

2024-10-21 16:21 UTC, Razew commented on screens/RegisterScreen.tsx
> +              <TouchableOpacity onPress={() => handleNavigate()}>
No need to create a "new" function since it doesn't take any parameters and already exists, so just gotta reference it
```suggestion
              <TouchableOpacity onPress={handleNavigate}>
```

2024-10-21 16:21 UTC, Razew commented on screens/LoginScreen.tsx
> +                onPress={() => handleLogin()}
No need to create a "new" function since it doesn't take any parameters, just need to reference it
```suggestion
                onPress={handleLogin}
```

2024-10-21 16:21 UTC, Razew commented on screens/LoginScreen.tsx
> +                <TouchableOpacity onPress={() => handleNavigate()}>
No need to create a "new" function since it doesn't take any parameters, just need to reference it
```suggestion
                <TouchableOpacity onPress={handleNavigate}>
```

2024-10-21 16:21 UTC, Razew commented on store/Auth/slice.ts
> +
Add a type for **CredentialsPayload** to use in place of { username: string; password: string } _(see suggestions below for where)_
```suggestion
type CredentialsPayload = { username: string; password: string };
```

2024-10-21 16:21 UTC, Razew commented on store/Auth/slice.ts
> +    { username, password }: { username: string; password: string },
```suggestion
    { username, password }: CredentialsPayload,
```

2024-10-21 16:21 UTC, Razew commented on store/Auth/slice.ts
> +    { username, password }: { username: string; password: string },
```suggestion
    { username, password }: CredentialsPayload,
```

2024-10-21 17:39 UTC, Razew approved these changes
![coding](https://github.com/user-attachments/assets/87c133bc-8c42-4b19-87e2-f0fa417f249f)
Nice!

2024-10-21 17:39 UTC, merged